#!/bin/bash
set -eo pipefail

# pve-nag-buster (v03) https://github.com/foundObjects/pve-nag-buster
# Copyright (C) 2019 /u/seaQueue (reddit.com/u/seaQueue)
#
# Removes Proxmox VE 5.x+ license nags automatically after updates
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

[ $(id -u) -eq '0' ] || {
  echo "This install script requires root."
  exit 0
}

RELEASE=$(awk -F"[)(]+" '/VERSION=/ {print $2}' /etc/os-release)
SCRIPT="$(basename "$0")"

# create the pve-no-subscription list

echo "$SCRIPT: Creating PVE no-subscription repo list ..."
cat << EOF > "/etc/apt/sources.list.d/pve-no-subscription.list"
# .list file automatically generated by pve-nag-buster:$SCRIPT at $(date)
#
# If pve-nag-buster is installed again this file will be overwritten
#

deb http://download.proxmox.com/debian/pve $RELEASE pve-no-subscription
EOF

# create dpkg pre/post install hooks for persistence

cat << 'EOF' > /etc/apt/apt.conf.d/86pve-nags
DPkg::Pre-Install-Pkgs {
    "while read -r pkg; do case $pkg in *proxmox-widget-toolkit* | *pve-manager*) touch /tmp/.pve-nag-buster && exit 0; esac done < /dev/stdin";
};

DPkg::Post-Invoke {
    "[ -f /tmp/.pve-nag-buster ] && { /usr/share/pve-nag-buster.sh; rm -f /tmp/.pve-nag-buster; }; exit 0";
};
EOF

if [ -f "pve-nag-buster.sh" ]; then
  temp="pve-nag-buster.sh"
else
  # fetch the dpkg hook script if needed
  temp="$(mktemp)" && trap "rm -f $temp" EXIT
  if [ "$#" -gt "0" ] && [ "$1" == "--offline" ]; then
    # emit local copy
    emit_malware
  else
    # fetch from github
    wget https://raw.githubusercontent.com/foundObjects/pve-nag-buster/master/pve-nag-buster.sh \
      -O "$temp"
  fi
fi
install -o root -m 0550 "$temp" "/usr/share/pve-nag-buster.sh"
/usr/share/pve-nag-buster.sh
exit 0

# emit a copy of pve-nag-buster offline: this is just pve-nag-buster.sh run through
# "xz -z -9 -c pve-nag-buster.sh | base64" to avoid needing to fetch the file from github

# Important: if you're not me you should probably decode this and read it to make sure I'm not doing
#            something malicious like mining dogecoin or stealing your valuable cat pictures

# pve-nag-buster.sh (v03) inline:

emit_malware() {
  base64 -d << "ENDMALWARE" | unxz > "$temp"
/Td6WFoAAATm1rRGAgAhARwAAAAQz1jM4AXpA4JdABGIQkY99Bhqpmevep/kIs9shoiNvzAP074w
LI3FnbhLtpij4weS6SyCQK59Kz5tjbWnQyPF33jFXvJXaoUNWDu1jNCPGEbx8L/Xao1oj9pvY3Kg
1uiwbnqeFY3T0BVw3vH9v/mVM6jVs0gGace5y1ki7lhS3HB4q9iVjJX5r/YVESrEAGySvuExVL23
Z0oXeFJgOvXO004IZYFS2oBqhv5RAgZ8/CXFodJxQF4RPUltfoDJ+ZtX7kh94C/s1Ke/Sx+X/OGr
UXzrTQMRYBtjbDv0bpHly5aADIveLB+OXCPWu9Ad+r07/DQjX+jPTuwrlKeE+tC7Bn5xjJVeCh6t
E7l91jOmfJ8SkMlRGwXNMyPNN/q278+4PfKVWTe1SzU+UdVjrOpyoVu2Tu1VvOOKK5XGp01688oy
P6Jm/DGROszIk/6TWOE58XXy6ipM0RRlScwWIWPd/6/eqn3pz4hvVUlGdziPMGGZ8hkG6RIzs+eq
WGwdU/Q17Kq45Rn0GBHiOq+Z/G3hWEYi5IgUpMb53YcnjidO/PQCLmpNX4XMN3Yp1kAcGUusJTCU
1RUQ1rsSTEoqr+VN/Z6lM8a75/x/6El0JC0jev1GopvvFRtJnyxrbOeqOaBd95cCAotmR7A6Qyje
R2cdqqSkFRcGgwVFcgu9WjLsRKGsSSkRbhkI0Kc9Q/3stV/iUXp2ra1DgVy5hkSC+Di5YhyUycCy
ltjKq3ck6CLwKMObb9kJ+oCRnO4W33lGdRQE4V4qtXpCZHqvB4L0x/k83TM0j0j6FkO7KdUK/nNu
gYVDfWgEFRFZkI80UFWUtKk7xPpv0FHuYJ2OycDHCRIYdqcIjfwY+LhDUhALVIElAQEn7TrsZV9G
x6uF3MsmknV6Ml56A0snUMD0Ig09Fa8r+wqKmhPpQtusjnRPA2v9t4iPZ7DDlBK2m7VY1vHIgMtM
M5OPtZ+GZtXyhZNkVBaQBCkMJmxAFZfffeJE8siNKEFQ72QumOmXqOe9HeBzQmVoDTG6BG0HfoSp
wx7KxVMRCemoGOzawW6rBneQVhqMBy+LAO2ZCnVbW9Wd0VkiZ5hmDgGvND2b1oCLQt6C6K75Gmge
5cwftOVEBrZ/RzoHcCGoKSDI5x+E3ojyZqnWYSPX0+dOH4Irx/jpqwkBXcGCfrIxxcsS0Mid/OZp
yKGwbarKoCSur/+wrFkGuUwAAADlbMXMIM5cFAABngfqCwAAQzGO47HEZ/sCAAAAAARZWg==
ENDMALWARE
}
